//! MIDI 2.0 / Universal MIDI Packet (UMP) core — pure, self-contained.
//!
//! This module tree adds a MIDI 2.0 layer to cosmix-musicd without touching
//! the existing MIDI 1.0 paths (`smf.rs`, `live.rs`, rustysynth rendering).
//! It is bit-twiddling over `u32` words: no FFI, no runtime deps, compiles
//! under `--no-default-features` (the purity gate).
//!
//! Layering (each layer only uses the ones above it):
//!
//! - [`ump`] — raw packet layer: 32/64/96/128-bit packets, the Message Type
//!   (MT) → word-count table, raw routing-nibble access, word-stream iteration.
//! - [`cv1`] / [`cv2`] — complete MIDI 1.0 and MIDI 2.0 Channel Voice
//!   families, retaining reserved bits for exact decode/re-encode.
//! - [`msg`] — typed Utility, System, SysEx7, Data128 and Channel Voice
//!   decoding with total unknown handling and semantic optional groups.
//! - [`bytestream`] — strict MIDI 1.0 wire parsing, explicit-status
//!   serialisation and identity-theorem canonicalisation.
//! - [`scale`] — the spec's default-translation bit-scaling primitives
//!   (7↔16, 7↔32, 14↔32), integer-exact min-center-max semantics.
//! - [`translate`] / [`up`] / [`down`] — fixed-capacity translation output,
//!   stateful idiom folding, canonical re-expansion and explicit loss counts.
//! - [`umpfile`] — the versioned, cos-internal `.cosump` working container.
//! - [`smfio`] — CLI-only SMF timeline merge/import/export bridge.
//!
//! ## The load-bearing invariant
//!
//! Up-translate then down-translate is the identity for every MIDI 1.0
//! channel-voice stream: `down(up(m1)) == canonicalize(m1)`. The reverse
//! direction is lossy by design (16→7-bit scaling, per-note controllers
//! dropped) and must be lossy in exactly the way the default-translation
//! rules say — losses are counted, never silent.
//!
//! ## Spec sources and attribution
//!
//! The normative MIDI Association *Universal MIDI Packet (UMP) Format and
//! MIDI 2.0 Protocol* PDF (M2-104-UM) was unavailable in this environment.
//! The local reference implementations below therefore act as the Phase 1
//! spec witnesses. Translation constants are cross-checked wherever two
//! witnesses expose the rule and pinned in tests; explicit reference gaps
//! are recorded in the decision log:
//!
//! - `ni-midi2` (github.com/midi2-dev/ni-midi2, MIT) — packet model and
//!   test vectors.
//! - `AM_MIDI2.0Lib` (github.com/midi2-dev/AM_MIDI2.0Lib, MIT) — scaling
//!   and translator reference; the pinned scaling vectors in [`scale`]
//!   were generated by running its `M2Utils::scaleUp` directly.
//! - `bl-midi2-rs` (github.com/midi2-dev/bl-midi2-rs, MIT/Apache-2.0) —
//!   Rust UMP type cross-check.
//!
//! No code was copied from these projects; they serve as spec witnesses
//! (the normative PDFs are registration-gated). Where a comment cites
//! "ni-midi2" or "AM lib" it names the file the constant was verified
//! against.
//!
//! ## Decision log
//!
//! 1. Both translators return an allocation-free four-slot `Translation<T>`.
//! 2. MIDI 1.0 CC96/97 remain ordinary MIDI 2.0 Control Change messages.
//! 3. Note-On velocity zero becomes Note Off velocity `0x8000`.
//! 4. Lone CC6 means `up14to32(msb << 7)` and is drained by `flush()`;
//!    **REFERENCE-GAP(M2-115-BT):** only AM has the stateful rule.
//! 5. Downscaled M2 Note On velocity zero is clamped to MIDI 1 velocity one.
//! 6. Down-translation always emits the full four-CC (N)RPN sequence;
//!    **REFERENCE-GAP(M2-115-BT):** NI's converter omits this family.
//! 7. CC0/32 bank a Program Change only when both halves are known; a lone
//!    half survives unbanked Program Changes and is consumed only by a later
//!    banked one (or dropped at flush), matching AM's 255-sentinel state;
//!    **REFERENCE-GAP(M2-115-BT):** only AM implements the state machine.
//! 8. Scaling is the integer min-centre-max bit-repeat algorithm in [`scale`].
//! 9. Delta Clockstamp carries tick deltas; tempo lives in the cos-local
//!    `.cosump` header; atomic SysEx timing/order changes are counted losses.
//! 10. [`bytestream::canonicalize`] expands running status, normalises
//!     Note-On zero, (N)RPN and bank idioms, and otherwise preserves order;
//!     selector halves update independently and retain the opposite half.
//! 11. Unknown MT/status packets and reserved bits re-encode byte-exact;
//!     SysEx topology is one per-group validator shared by raw I/O and SMF.
//! 12. The identity theorem covers valid parsed channel-voice streams, not
//!     malformed byte soup, raw SMF bytes, track topology, or dropped metadata.
//!
//! Promotion note: the packet/message/scaling/translation layers are
//! deliberately `no_std`-shaped. The byte-stream convenience APIs use `Vec`
//! for event lists; typed SysEx fragments are UMP-sized and bounded to six
//! bytes. No dependency beyond `std` is added.
//! If a second crate ever needs the layer (e.g. cosmix-song going native-M2),
//! promote it to `cosmix-lib-midi2` — not before.

pub mod bytestream;
pub mod cv1;
pub mod cv2;
pub mod down;
pub mod msg;
pub mod scale;
pub mod smfio;
pub mod translate;
pub mod ump;
pub mod umpfile;
pub mod up;
