//! Default-translation bit-scaling primitives (MIDI 1.0 ↔ MIDI 2.0).
//!
//! The spec's min-center-max algorithm, integer-exact: values at or below
//! the source center are a plain left shift (so 0 → 0 and center → center:
//! 64 → 0x8000, 8192 → 0x80000000); values above center fill the vacated
//! low bits by repeating the significant bits, so the source maximum maps
//! to the destination maximum (127 → 0xFFFF / 0xFFFFFFFF, 16383 →
//! 0xFFFFFFFF). Down-scaling is truncation (keep the top bits), which
//! preserves all three anchors and makes `down(up(v)) == v` hold for every
//! source value — tested exhaustively below.
//!
//! Verified against AM_MIDI2.0Lib `include/utils.h` (`M2Utils::scaleUp`/
//! `scaleDown`); the pinned vectors in the tests were generated by running
//! that code directly.

/// The spec up-scaling algorithm for arbitrary widths. `src_bits` must be
/// ≥ 2 (the spec's 1-bit special case never occurs here: our sources are
/// 7- and 14-bit) and `dst_bits` > `src_bits` ≥ the value's width.
const fn scale_up(src_val: u32, src_bits: u32, dst_bits: u32) -> u32 {
    if src_val == 0 {
        return 0;
    }
    let scale_bits = dst_bits - src_bits;
    let bit_shifted = src_val << scale_bits;
    let src_center = 1u32 << (src_bits - 1);
    if src_val <= src_center {
        return bit_shifted;
    }
    // Above center: repeat the significant bits (all but the top bit) into
    // the vacated low bits until they run out.
    let repeat_bits = src_bits - 1;
    let repeat_mask = (1u32 << repeat_bits) - 1;
    let mut repeat_value = src_val & repeat_mask;
    if scale_bits > repeat_bits {
        repeat_value <<= scale_bits - repeat_bits;
    } else {
        repeat_value >>= repeat_bits - scale_bits;
    }
    let mut out = bit_shifted;
    while repeat_value != 0 {
        out |= repeat_value;
        repeat_value >>= repeat_bits;
    }
    out
}

/// 7-bit (0..=127) → 16-bit, min-center-max. 0→0, 64→0x8000, 127→0xFFFF.
pub const fn up7to16(v: u8) -> u16 {
    debug_assert!(v <= 0x7F);
    // Result of a 7→16 scale always fits in 16 bits.
    scale_up(v as u32, 7, 16) as u16
}

/// 7-bit (0..=127) → 32-bit, min-center-max. 0→0, 64→0x8000_0000, 127→0xFFFF_FFFF.
pub const fn up7to32(v: u8) -> u32 {
    debug_assert!(v <= 0x7F);
    scale_up(v as u32, 7, 32)
}

/// 14-bit (0..=16383) → 32-bit, min-center-max. 0→0, 8192→0x8000_0000,
/// 16383→0xFFFF_FFFF.
pub const fn up14to32(v: u16) -> u32 {
    debug_assert!(v <= 0x3FFF);
    scale_up(v as u32, 14, 32)
}

/// 16-bit → 7-bit: truncate to the top 7 bits. 0x8000→64, 0xFFFF→127.
pub const fn down16to7(v: u16) -> u8 {
    // Top 7 of 16 bits always fit in u8.
    (v >> 9) as u8
}

/// 32-bit → 7-bit: truncate to the top 7 bits. 0x8000_0000→64, 0xFFFF_FFFF→127.
pub const fn down32to7(v: u32) -> u8 {
    // Top 7 of 32 bits always fit in u8.
    (v >> 25) as u8
}

/// 32-bit → 14-bit: truncate to the top 14 bits. 0x8000_0000→8192,
/// 0xFFFF_FFFF→16383.
pub const fn down32to14(v: u32) -> u16 {
    // Top 14 of 32 bits always fit in u16.
    (v >> 18) as u16
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn anchors() {
        assert_eq!(up7to16(0), 0);
        assert_eq!(up7to16(64), 0x8000);
        assert_eq!(up7to16(127), 0xFFFF);
        assert_eq!(up7to32(0), 0);
        assert_eq!(up7to32(64), 0x8000_0000);
        assert_eq!(up7to32(127), 0xFFFF_FFFF);
        assert_eq!(up14to32(0), 0);
        assert_eq!(up14to32(8192), 0x8000_0000);
        assert_eq!(up14to32(16383), 0xFFFF_FFFF);
        assert_eq!(down16to7(0x8000), 64);
        assert_eq!(down32to7(0x8000_0000), 64);
        assert_eq!(down32to14(0x8000_0000), 8192);
    }

    /// Vectors generated by running AM_MIDI2.0Lib's `M2Utils::scaleUp`
    /// (include/utils.h) directly — see the module doc.
    #[test]
    fn reference_vectors() {
        const V7_16: &[(u8, u16)] = &[
            (1, 0x0200),
            (3, 0x0600),
            (25, 0x3200),
            (63, 0x7E00),
            (64, 0x8000),
            (65, 0x8208),
            (100, 0xC924),
            (126, 0xFDF7),
            (127, 0xFFFF),
        ];
        for &(v, want) in V7_16 {
            assert_eq!(up7to16(v), want, "up7to16({v})");
        }
        const V7_32: &[(u8, u32)] = &[
            (1, 0x0200_0000),
            (3, 0x0600_0000),
            (25, 0x3200_0000),
            (63, 0x7E00_0000),
            (64, 0x8000_0000),
            (65, 0x8208_2082),
            (100, 0xC924_9249),
            (126, 0xFDF7_DF7D),
            (127, 0xFFFF_FFFF),
        ];
        for &(v, want) in V7_32 {
            assert_eq!(up7to32(v), want, "up7to32({v})");
        }
        const V14_32: &[(u16, u32)] = &[
            (1, 0x0004_0000),
            (100, 0x0190_0000),
            (4096, 0x4000_0000),
            (8191, 0x7FFC_0000),
            (8192, 0x8000_0000),
            (8193, 0x8004_0020),
            (12000, 0xBB81_DC0E),
            (16382, 0xFFFB_FFDF),
            (16383, 0xFFFF_FFFF),
        ];
        for &(v, want) in V14_32 {
            assert_eq!(up14to32(v), want, "up14to32({v})");
        }
    }

    /// The round-trip law over the ENTIRE source domains.
    #[test]
    fn down_up_identity_exhaustive() {
        for v in 0u8..=127 {
            assert_eq!(down16to7(up7to16(v)), v, "16↔7 {v}");
            assert_eq!(down32to7(up7to32(v)), v, "32↔7 {v}");
        }
        for v in 0u16..=16383 {
            assert_eq!(down32to14(up14to32(v)), v, "32↔14 {v}");
        }
    }

    /// Strict monotonicity — required for the identity law to even be
    /// possible, and it pins the "no value collapses" property.
    #[test]
    fn up_strictly_monotonic() {
        for v in 1u8..=127 {
            assert!(up7to16(v - 1) < up7to16(v), "7to16 at {v}");
            assert!(up7to32(v - 1) < up7to32(v), "7to32 at {v}");
        }
        for v in 1u16..=16383 {
            assert!(up14to32(v - 1) < up14to32(v), "14to32 at {v}");
        }
    }
}
