    fn version_repo() -> (tempfile::TempDir, PathBuf, String) {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repo");
        std::fs::create_dir(&repo).unwrap();
        git(&repo, &["init", "-b", "main"]).unwrap();
        git(&repo, &["config", "user.name", "test"]).unwrap();
        git(&repo, &["config", "user.email", "test@example.com"]).unwrap();
        std::fs::create_dir_all(repo.join("crate/src")).unwrap();
        std::fs::write(
            repo.join("Cargo.toml"),
            "[workspace]\nmembers=['crate']\n[workspace.package]\nversion='0.1.0'\n",
        )
        .unwrap();
        std::fs::write(
            repo.join("crate/Cargo.toml"),
            "[package]\nname='fixture'\nversion.workspace=true\nedition='2024'\n",
        )
        .unwrap();
        std::fs::write(repo.join("crate/src/lib.rs"), "pub fn base() {}\n").unwrap();
        std::fs::write(
            repo.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"fixture\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        git(&repo, &["add", "."]).unwrap();
        git(&repo, &["commit", "-m", "base"]).unwrap();
        let base = git(&repo, &["rev-parse", "HEAD"])
            .unwrap()
            .trim()
            .to_string();
        (tmp, repo, base)
    }

    fn version_task(db: &Path) -> Task {
        let ledger = Ledger::open(db).unwrap();
        let id = ledger
            .add_task("version fixture", "spec", "impl", "low", &[], "none")
            .unwrap();
        ledger.task(id).unwrap().unwrap()
    }

    #[test]
    fn task_fault_preserves_inner_infrastructure_classification() {
        let error = task_fault(
            infrastructure_message("injected host I/O").context("reading workspace lockfile"),
        );
        assert!(
            error.downcast_ref::<LandingInfrastructure>().is_some(),
            "{error:#}"
        );
        assert!(error.downcast_ref::<LandingTaskFault>().is_none());
    }

    #[test]
    fn landing_implementation_run_read_wraps_ledger_failure_as_infrastructure() {
        let tmp = tempfile::tempdir().unwrap();
        let db = tmp.path().join("broken-ledger.db");
        let ledger = Ledger::open(&db).unwrap();
        rusqlite::Connection::open(&db)
            .unwrap()
            .execute_batch("DROP TABLE runs")
            .unwrap();

        let error = latest_implementation_run_for_landing(&ledger, 1, "reading run").unwrap_err();
        assert!(
            error.downcast_ref::<LandingInfrastructure>().is_some(),
            "{error:#}"
        );
    }

    #[test]
    fn cargo_child_failures_separate_local_resolution_from_ambiguous_host_faults() {
        let worktree = Path::new("/fixture/worktree");
        let manifest = cargo_child_failure(
            "cargo metadata",
            "error: failed to parse manifest at /fixture/worktree/Cargo.toml",
            worktree,
        );
        assert!(manifest.downcast_ref::<LandingTaskFault>().is_some());

        for stderr in [
            "error: No space left on device (os error 28)",
            "error: failed to parse manifest at /fixture/worktree/Cargo.toml: Input/output error",
            "error: failed to parse manifest at /cache/registry/pkg/Cargo.toml",
            "error: package cache checksum failed",
        ] {
            let error = cargo_child_failure("cargo metadata", stderr, worktree);
            assert!(
                error.downcast_ref::<LandingInfrastructure>().is_some(),
                "{error:#}"
            );
        }
    }

    #[test]
    fn slow_cargo_child_is_killed_reaped_and_uses_infrastructure_backoff() {
        let tmp = tempfile::tempdir().unwrap();
        let pid_file = tmp.path().join("slow-cargo.pid");
        let mut command = Command::new("sh");
        command
            .args([
                "-c",
                "printf '%s\\n' \"$$\" > \"$1\"; while :; do sleep 1; done",
                "slow-cargo",
            ])
            .arg(&pid_file);
        let error = run_bounded_cargo_child(
            command,
            "cargo metadata --offline test stub",
            Duration::from_millis(250),
        )
        .unwrap_err();
        assert!(
            error.downcast_ref::<LandingInfrastructure>().is_some(),
            "{error:#}"
        );
        assert!(
            error
                .to_string()
                .contains("cargo metadata --offline test stub timed out after 250ms"),
            "{error:#}"
        );
        let pid: i32 = std::fs::read_to_string(&pid_file)
            .unwrap()
            .trim()
            .parse()
            .unwrap();
        let alive = unsafe { libc::kill(pid, 0) };
        assert_eq!(alive, -1, "timed-out cargo stub {pid} was not reaped");
        assert_eq!(
            std::io::Error::last_os_error().raw_os_error(),
            Some(libc::ESRCH)
        );

        let ledger = Ledger::open(&tmp.path().join("ledger.db")).unwrap();
        let id = ledger
            .add_task("cargo lock contention", "spec", "impl", "low", &[], "none")
            .unwrap();
        ledger.claim_task(id, "agent").unwrap();
        ledger.finish_task(id, "agent", "done").unwrap();
        let task = ledger.task(id).unwrap().unwrap();
        assert!(ledger.transition_if(id, "done", "landing").unwrap());
        let report = landing_error_report(&task, &error);
        assert_eq!(report.reason, FindingReason::InfraRefusal);
        finish_landing_and_maybe_wake(
            &ledger,
            id,
            "bounced",
            None,
            &report,
            3,
            10,
            crate::ledger::DEFAULT_BRANCH_CONTRACT_LIMIT,
            chrono::Utc::now(),
            || {},
        )
        .unwrap();
        let task = ledger.task(id).unwrap().unwrap();
        assert_eq!(task.status, "bounced");
        assert_eq!(task.infra_refusals, 1);
        assert_eq!(task.branch_contract_failures, 0);
        assert!(task.dispatch_after.is_some());
    }

    #[test]
    fn pipe_holding_grandchild_does_not_wedge_the_capture_join_past_the_deadline() {
        let tmp = tempfile::tempdir().unwrap();
        let direct_pid_file = tmp.path().join("direct.pid");
        let grandchild_pid_file = tmp.path().join("grandchild.pid");
        let mut command = Command::new("sh");
        command
            .args([
                "-c",
                "printf '%s\\n' \"$$\" > \"$1\"; \
                 ( while :; do sleep 1; done ) & \
                 printf '%s\\n' \"$!\" > \"$2\"; \
                 exit 0",
                "grandchild-hang",
            ])
            .arg(&direct_pid_file)
            .arg(&grandchild_pid_file);
        let started = Instant::now();
        // The DIRECT child exits immediately, leaving behind a backgrounded
        // grandchild that inherited the stdout/stderr pipes and never
        // closes them. Before this fix the post-exit join was unconditional
        // and would hang forever on exactly this shape.
        let error = run_bounded_cargo_child(
            command,
            "cargo metadata --offline test stub",
            Duration::from_millis(200),
        )
        .unwrap_err();
        assert!(
            started.elapsed() < Duration::from_secs(5),
            "the capture join was not bounded by the deadline: took {:?}",
            started.elapsed()
        );
        assert!(
            error.downcast_ref::<LandingInfrastructure>().is_some(),
            "{error:#}"
        );
        assert!(
            error.to_string().contains("reader did not drain"),
            "{error:#}"
        );

        let grandchild_pid: i32 = std::fs::read_to_string(&grandchild_pid_file)
            .unwrap()
            .trim()
            .parse()
            .unwrap();
        // The grandchild is orphaned to init the moment its parent (the
        // already-exited, already-reaped `sh`) goes away, so SIGKILL leaves
        // it a zombie (`kill(pid, 0)` still succeeds) until init's reaper
        // gets around to it. Poll rather than assert on the instant.
        let reap_deadline = Instant::now() + Duration::from_secs(5);
        loop {
            let alive = unsafe { libc::kill(grandchild_pid, 0) };
            if alive == -1 && std::io::Error::last_os_error().raw_os_error() == Some(libc::ESRCH) {
                break;
            }
            assert!(
                Instant::now() < reap_deadline,
                "pipe-holding grandchild {grandchild_pid} was not reaped"
            );
            std::thread::sleep(Duration::from_millis(25));
        }
    }

    #[test]
    fn exceeding_the_output_cap_is_a_diagnosed_task_fault_not_infrastructure() {
        // A real cos workspace `cargo metadata --offline --no-deps` run is
        // ~0.18 MiB, 22x under the 4 MiB cap (measured 2026-08-27) — hitting
        // the cap is this invocation's own runaway output, not a sign of
        // host trouble, and must not retry forever as infrastructure.
        let mut command = Command::new("sh");
        command.args([
            "-c",
            &format!("yes | head -c {}", CARGO_CHILD_OUTPUT_LIMIT + 1),
        ]);
        let error = run_bounded_cargo_child(
            command,
            "cargo metadata output-cap test stub",
            Duration::from_secs(30),
        )
        .unwrap_err();
        assert!(
            error.downcast_ref::<LandingInfrastructure>().is_none(),
            "{error:#}"
        );
        let fault = error
            .downcast_ref::<LandingTaskFault>()
            .unwrap_or_else(|| panic!("expected a task fault, got: {error:#}"));
        assert_eq!(fault.reason, FindingReason::BranchContract);
        assert!(
            fault
                .detail
                .contains("cargo metadata output-cap test stub exceeded the bounded"),
            "{fault:?}"
        );
    }
