d /var/lib/cosmix/nspawnd             0700 cosmix-nspawnd cosmix-nspawnd -
d /var/lib/cosmix/nspawnd/tombstones  0700 cosmix-nspawnd cosmix-nspawnd -
d /var/lib/cosmix/nspawnd/grants      0700 cosmix-nspawnd cosmix-nspawnd -
d /var/lib/cosmix/nspawnd/instances   0700 cosmix-nspawnd cosmix-nspawnd -
d /var/lib/cosmix/nspawnd/operations  0700 cosmix-nspawnd cosmix-nspawnd -
d /var/lib/cosmix/nspawnd/operations/requests 0700 cosmix-nspawnd cosmix-nspawnd -
d /run/lock/cosmix-nspawnd            0700 cosmix-nspawnd cosmix-nspawnd -
