[package]
name = "cosmix-wl-dnd"
version = "0.4.2"
edition = "2024"
publish = false

[dependencies]
getrandom = "=0.4.3"
libc = "=0.2.186"
percent-encoding = "=2.3.2"
raw-window-handle = "=0.6.2"
smithay-client-toolkit = { version = "=0.19.2", default-features = false }
wayland-backend = { version = "=0.3.15", features = ["client_system"] }
wayland-client = "=0.31.14"
