//! Landing reuses the completed task worktree for verification, then reclaims
//! its pinned private target after the terminal disposition is durable.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::OnceLock;

use cosmix_foreman::config::FleetPolicy;
use cosmix_foreman::ledger::{ClaimToken, Ledger, TaskControls};
use cosmix_foreman::refinery::{self, RefineOptions};
use cosmix_foreman::verify::VerifyReport;

static TOOL_PATH: OnceLock<tempfile::TempDir> = OnceLock::new();
const HELPER_ENV: &str = "COSMIX_FOREMAN_LANDING_TARGET_HELPER";

fn test_tool_path() -> &'static Path {
    let tools = TOOL_PATH.get_or_init(|| {
        let dir = tempfile::tempdir().unwrap();
        for tool in [
            "cargo",
            "cargo-clippy",
            "cargo-fmt",
            "clippy-driver",
            "rustc",
            "rustdoc",
            "rustfmt",
            "cc",
            "ld",
            "ar",
            "git",
            "sh",
            "timeout",
        ] {
            std::os::unix::fs::symlink(Path::new("/usr/bin").join(tool), dir.path().join(tool))
                .unwrap();
        }
        dir
    });
    tools.path()
}

fn run_owned_helper(name: &str) {
    let out = Command::new(std::env::current_exe().unwrap())
        .args([
            "--exact",
            name,
            "--ignored",
            "--nocapture",
            "--test-threads=1",
        ])
        .env(HELPER_ENV, name)
        .env("PATH", test_tool_path())
        .env("RUSTC_WRAPPER", "")
        .output()
        .expect("spawn owned landing-target helper");
    assert!(
        out.status.success(),
        "owned helper {name} failed\n--- stdout ---\n{}\n--- stderr ---\n{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
}

fn assert_owned_helper(name: &str) {
    assert_eq!(std::env::var(HELPER_ENV).as_deref(), Ok(name));
}

fn git(repo: &Path, args: &[&str]) {
    let output = Command::new("git")
        .args(args)
        .current_dir(repo)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "git {args:?} failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn repository(root: &Path) -> PathBuf {
    let repo = root.join("repo");
    std::fs::create_dir(&repo).unwrap();
    git(&repo, &["init", "-b", "main"]);
    git(&repo, &["config", "user.name", "test"]);
    git(&repo, &["config", "user.email", "test@example.com"]);
    std::fs::create_dir_all(repo.join("src/src")).unwrap();
    std::fs::write(
        repo.join("src/Cargo.toml"),
        "[package]\nname = \"landing-probe\"\nversion = \"0.1.0\"\nedition = \"2024\"\nlicense = \"MIT\"\n",
    )
    .unwrap();
    std::fs::write(repo.join("src/src/lib.rs"), "pub fn value() -> u8 { 1 }\n").unwrap();
    std::fs::write(repo.join(".gitignore"), "/src/target\n").unwrap();
    // Tier 1 runs `cargo deny check` when the real binary is on PATH (this
    // fixture no longer hides it behind a curated fake PATH — see the PATH
    // comment in the test below). cargo-deny's own default template denies
    // any license absent an explicit allow-list, so the fixture needs one
    // for its own MIT declaration to pass.
    std::fs::write(
        repo.join("src/deny.toml"),
        "[licenses]\nallow = [\"MIT\"]\n",
    )
    .unwrap();
    std::fs::write(
        repo.join("src/Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\n\
         [[package]]\n\
         name = \"landing-probe\"\n\
         version = \"0.1.0\"\n",
    )
    .unwrap();
    git(&repo, &["add", "."]);
    git(&repo, &["commit", "-m", "base"]);
    repo
}

#[test]
fn tier1_landing_reuses_then_reclaims_task_target_and_carries_provenance_once() {
    run_owned_helper(
        "tier1_landing_reuses_then_reclaims_task_target_and_carries_provenance_once_owned_process",
    );
}

#[test]
#[ignore = "run only in the owned helper process"]
fn tier1_landing_reuses_then_reclaims_task_target_and_carries_provenance_once_owned_process() {
    assert_owned_helper(
        "tier1_landing_reuses_then_reclaims_task_target_and_carries_provenance_once_owned_process",
    );
    let tmp = tempfile::tempdir().unwrap();
    let repo = repository(tmp.path());
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let id = ledger
        .add_task_scoped(
            "reuse target",
            "spec",
            "impl",
            "low",
            &[],
            TaskControls {
                verifier_profile: "rust",
                crates: &["landing-probe".to_string()],
                operator_driven_reason: None,
            },
        )
        .unwrap();
    let branch = format!("task/{id}");
    // Use a manifest-style custom worktree location so landing must trust
    // and validate the ledger-recorded checkout, not reconstruct task-<id>.
    let task_worktree = refinery::ensure_task_worktree_named_in(
        &repo,
        id,
        &branch,
        None,
        "warm-task-{id}",
        Some(tmp.path()),
    )
    .unwrap()
    .path;
    std::fs::write(
        task_worktree.join("src/src/lib.rs"),
        "pub fn value() -> u8 {\n    2\n}\n\n#[test]\nfn changed() {\n    assert_eq!(value(), 2);\n}\n",
    )
    .unwrap();
    git(&task_worktree, &["add", "src/src/lib.rs"]);
    git(&task_worktree, &["commit", "-m", "task change"]);
    let marker = task_worktree.join("src/target/agent-warm-marker");
    std::fs::create_dir_all(marker.parent().unwrap()).unwrap();
    std::fs::write(&marker, "warm\n").unwrap();
    let sibling_marker = tmp
        .path()
        .join(format!("task-{id}-target/agent-warm-marker"));
    std::fs::create_dir_all(sibling_marker.parent().unwrap()).unwrap();
    std::fs::write(&sibling_marker, "legacy warm\n").unwrap();

    let claimed = ledger.claim_task(id, "agent").unwrap();
    ledger
        .set_task_workspace(
            id,
            ClaimToken {
                owner: "agent",
                generation: claimed.attempt,
            },
            Some(task_worktree.to_string_lossy().as_ref()),
            Some(&branch),
        )
        .unwrap();
    ledger.finish_task(id, "agent", "done").unwrap();

    let reports = refinery::refine(
        &ledger,
        &RefineOptions {
            repo: repo.clone(),
            project_root: Some(tmp.path().to_path_buf()),
            integration: "main".into(),
            subdir: "src".into(),
            tier: 1,
            review: false,
            db,
            echo: false,
            fleet_policy: Some(FleetPolicy::defaults()),
            profiles: Vec::new(),
            project_pack: String::new(),
            landing_gate: None,
            lane_policy: None,
        },
    )
    .unwrap();
    assert_eq!(reports.len(), 1);
    assert!(reports[0].landed, "{}", reports[0].detail);
    assert!(!marker.exists(), "landed task target must be reclaimed");
    assert!(
        !sibling_marker.exists(),
        "landed task sibling target must be reclaimed"
    );
    assert!(
        task_worktree.is_dir(),
        "scratch cleanup must retain the task worktree"
    );
    assert!(
        task_worktree.join("src/src/lib.rs").is_file(),
        "scratch cleanup must retain tracked source"
    );

    let stored = ledger.verification_reports(id, 10).unwrap();
    let record: serde_json::Value = stored
        .iter()
        .map(|json| serde_json::from_str(json).unwrap())
        .find(|value: &serde_json::Value| value.get("report").is_some())
        .expect("landing tier report");
    let report: VerifyReport = serde_json::from_value(record["report"].clone()).unwrap();
    assert_eq!(report.provenance_tier, Some(1));
    assert_eq!(
        report
            .steps
            .iter()
            .filter(|step| step.executed_binaries.is_some())
            .count(),
        1,
        "landing report must carry provenance exactly once: {report:?}"
    );
    assert_eq!(
        Path::new(report.target_dir.as_deref().unwrap()),
        task_worktree.join("src/target")
    );
}

#[test]
fn landing_with_an_empty_profile_still_reclaims_the_task_target() {
    run_owned_helper("landing_with_an_empty_profile_still_reclaims_the_task_target_owned_process");
}

#[test]
#[ignore = "run only in the owned helper process"]
fn landing_with_an_empty_profile_still_reclaims_the_task_target_owned_process() {
    assert_owned_helper(
        "landing_with_an_empty_profile_still_reclaims_the_task_target_owned_process",
    );
    let tmp = tempfile::tempdir().unwrap();
    let repo = repository(tmp.path());
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let id = ledger
        .add_task_scoped(
            "reuse target without cargo gate",
            "spec",
            "impl",
            "low",
            &[],
            TaskControls {
                verifier_profile: "none",
                crates: &[],
                operator_driven_reason: None,
            },
        )
        .unwrap();
    let branch = format!("task/{id}");
    let task_worktree = refinery::ensure_task_worktree(&repo, id, &branch, None)
        .unwrap()
        .path;
    std::fs::write(
        task_worktree.join("src/src/lib.rs"),
        "pub fn value() -> u8 { 2 }\n",
    )
    .unwrap();
    git(&task_worktree, &["add", "src/src/lib.rs"]);
    git(&task_worktree, &["commit", "-m", "task change"]);
    let marker = task_worktree.join("src/target/agent-warm-marker");
    std::fs::create_dir_all(marker.parent().unwrap()).unwrap();
    std::fs::write(&marker, "warm\n").unwrap();

    let claimed = ledger.claim_task(id, "agent").unwrap();
    ledger
        .set_task_workspace(
            id,
            ClaimToken {
                owner: "agent",
                generation: claimed.attempt,
            },
            Some(task_worktree.to_string_lossy().as_ref()),
            Some(&branch),
        )
        .unwrap();
    ledger.finish_task(id, "agent", "done").unwrap();

    let reports = refinery::refine(
        &ledger,
        &RefineOptions {
            repo: repo.clone(),
            project_root: None,
            integration: "main".into(),
            subdir: "src".into(),
            tier: 1,
            review: false,
            db,
            echo: false,
            fleet_policy: Some(FleetPolicy::defaults()),
            profiles: Vec::new(),
            project_pack: String::new(),
            landing_gate: None,
            lane_policy: None,
        },
    )
    .unwrap();
    assert_eq!(reports.len(), 1);
    assert!(reports[0].landed, "{}", reports[0].detail);
    assert!(!marker.exists(), "landed task target must be reclaimed");
    assert!(
        task_worktree.is_dir(),
        "scratch cleanup must retain the task worktree"
    );
}
