//! Phase-2 tests: policy-gate rule table (pure evaluation over documented
//! PreToolUse payload shapes) and governor budget reservation (atomic
//! ceiling holds, release, expiry).

use std::path::PathBuf;
use std::process::{Command, Stdio};

use cosmix_foreman::driver::claude::ClaudeDriver;
use cosmix_foreman::driver::codex::CodexDriver;
use cosmix_foreman::executor::{AgentKind, Budget, Executor, RunOutcome, StopReason, Usage};
use cosmix_foreman::governor::Governor;
use cosmix_foreman::ledger::Ledger;
use cosmix_foreman::policy::{PolicyContext, Verdict, evaluate, resolve_integration_base};
use serde_json::json;

fn ctx(provider: &str, branch: Option<&str>) -> PolicyContext {
    PolicyContext {
        task_id: 7,
        worktree: PathBuf::from("/work/task7"),
        branch: branch.map(String::from),
        provider: provider.into(),
        integration_base: "HEAD".into(),
        integration_branch: "main".into(),
        task_ref_template: "task/{id}".into(),
        package_manifest_template: Some("src/crates/{crate}/Cargo.toml".into()),
        restrict_manifest_edits: false,
        task_crates: Vec::new(),
    }
}

fn call(tool: &str, input: serde_json::Value) -> serde_json::Value {
    json!({ "hook_event_name": "PreToolUse", "tool_name": tool, "tool_input": input })
}

/// A PRODUCTION-SHAPED worktree: the fleet home is `.foreman/` and every
/// task worktree lives inside it. The other tests use `/work/task7`, whose
/// path contains no gate fragment — which is exactly why absolute-path
/// gate matching passed them while denying every real in-worktree write.
fn fleet_ctx() -> PolicyContext {
    PolicyContext {
        task_id: 5,
        worktree: PathBuf::from("/home/op/.cmctl/.foreman/task-5"),
        branch: Some("task/5".into()),
        provider: "anthropic".into(),
        integration_base: "HEAD".into(),
        integration_branch: "main".into(),
        task_ref_template: "task/{id}".into(),
        package_manifest_template: Some("src/crates/{crate}/Cargo.toml".into()),
        restrict_manifest_edits: false,
        task_crates: Vec::new(),
    }
}

const OWN_MANIFEST: &str = "[package]\nname = \"own-crate\"\nversion = \"0.2.3\"\nedition = \"2024\"\n\n[dependencies]\nanyhow = \"1\"\n";
const OTHER_MANIFEST: &str =
    "[package]\nname = \"other-crate\"\nversion = \"1.4.0\"\nedition = \"2024\"\n";
const TEST_LOCK: &str = "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"other-crate\"\nversion = \"1.4.0\"\n\n[[package]]\nname = \"own-crate\"\nversion = \"0.2.3\"\n\n[[package]]\nname = \"own-crate\"\nversion = \"7.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"fixture\"\n";

struct PolicyRepo {
    _temp: tempfile::TempDir,
    root: PathBuf,
}

struct PushPolicyRepo {
    _temp: tempfile::TempDir,
    shared: PathBuf,
    worktree: PathBuf,
}

impl PushPolicyRepo {
    fn new() -> Self {
        let temp = tempfile::tempdir().unwrap();
        let shared = temp.path().join("workdir");
        let worktree = temp.path().join("task-7");
        std::fs::create_dir(&shared).unwrap();
        run_git(&shared, &["init", "-b", "main"]);
        run_git(&shared, &["config", "user.email", "fixture@example.com"]);
        run_git(&shared, &["config", "user.name", "Policy Fixture"]);
        std::fs::write(shared.join("base.txt"), "base\n").unwrap();
        run_git(&shared, &["add", "."]);
        run_git(&shared, &["commit", "-m", "fixture"]);
        run_git(&shared, &["branch", "task/7"]);
        run_git(
            &shared,
            &["worktree", "add", worktree.to_str().unwrap(), "task/7"],
        );
        Self {
            _temp: temp,
            shared,
            worktree,
        }
    }

    fn ctx(&self) -> PolicyContext {
        PolicyContext {
            task_id: 7,
            worktree: self.worktree.clone(),
            branch: Some("task/7".into()),
            provider: "anthropic".into(),
            integration_base: git_stdout(&self.shared, &["rev-parse", "main"]),
            integration_branch: "main".into(),
            task_ref_template: "task/{id}".into(),
            package_manifest_template: Some("src/crates/{crate}/Cargo.toml".into()),
            restrict_manifest_edits: false,
            task_crates: Vec::new(),
        }
    }
}

impl PolicyRepo {
    fn new() -> Self {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path().to_path_buf();
        for crate_name in ["own-crate", "other-crate"] {
            std::fs::create_dir_all(root.join("src/crates").join(crate_name).join("src")).unwrap();
            std::fs::write(
                root.join("src/crates").join(crate_name).join("src/lib.rs"),
                format!("pub const NAME: &str = {crate_name:?};\n"),
            )
            .unwrap();
        }
        std::fs::write(root.join("src/crates/own-crate/Cargo.toml"), OWN_MANIFEST).unwrap();
        std::fs::create_dir_all(root.join("desktop/crates/own-crate")).unwrap();
        std::fs::write(
            root.join("desktop/crates/own-crate/Cargo.toml"),
            OWN_MANIFEST,
        )
        .unwrap();
        std::fs::write(
            root.join("src/crates/other-crate/Cargo.toml"),
            OTHER_MANIFEST,
        )
        .unwrap();
        std::fs::write(root.join("src/Cargo.lock"), TEST_LOCK).unwrap();
        // Deliberately no `main`: policy scope must use the caller-resolved
        // integration base, never a hard-coded branch name.
        run_git(&root, &["init", "-b", "integration"]);
        run_git(&root, &["config", "user.email", "fixture@example.com"]);
        run_git(&root, &["config", "user.name", "Policy Fixture"]);
        run_git(&root, &["add", "."]);
        run_git(&root, &["commit", "-m", "fixture"]);
        run_git(&root, &["checkout", "-b", "task/7"]);
        Self { _temp: temp, root }
    }

    fn ctx(&self, crates: &[&str]) -> PolicyContext {
        let integration_base = git_stdout(&self.root, &["rev-parse", "integration"]);
        PolicyContext {
            task_id: 7,
            worktree: self.root.clone(),
            branch: Some("task/7".into()),
            provider: "anthropic".into(),
            integration_base,
            integration_branch: "integration".into(),
            task_ref_template: "task/{id}".into(),
            package_manifest_template: Some("src/crates/{crate}/Cargo.toml".into()),
            restrict_manifest_edits: false,
            task_crates: crates.iter().map(|name| (*name).to_string()).collect(),
        }
    }

    fn path(&self, relative: &str) -> String {
        self.root.join(relative).to_string_lossy().into_owned()
    }
}

fn run_git(dir: &std::path::Path, args: &[&str]) {
    let output = Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "git {args:?} failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn git_stdout(dir: &std::path::Path, args: &[&str]) -> String {
    let output = Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap();
    assert!(output.status.success(), "git {args:?} failed: {output:?}");
    String::from_utf8(output.stdout).unwrap().trim().to_string()
}

#[test]
fn policy_gates_are_worktree_relative() {
    let c = fleet_ctx();
    // THE REGRESSION (live 2026-08-18): ordinary work inside a worktree
    // that happens to sit under the fleet home must be ALLOWED. Denying it
    // left agents only relative-path shell editing — the one lane this
    // gate cannot check, i.e. the gate inverted its own purpose.
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": "/home/op/.cmctl/.foreman/task-5/src/crates/cosmix-foreman/src/refinery.rs"})
            )
        ),
        Verdict::Allow
    );
    // Bash naming the worktree absolutely is ordinary work too.
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": "cd /home/op/.cmctl/.foreman/task-5/src && cargo test -p cosmix-foreman"})
            )
        ),
        Verdict::Allow
    );
    // …while the enforcement rail stays denied at the same depth.
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": "/home/op/.cmctl/.foreman/task-5/src/crates/cosmix-foreman/src/policy.rs"})
            )
        ),
        Verdict::Deny(_)
    ));
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": "sed -i s/x/y/ /home/op/.cmctl/.foreman/task-5/src/crates/cosmix-foreman/src/policy.rs"})
            )
        ),
        Verdict::Deny(_)
    ));
    // A stray ledger nested INSIDE the worktree is still a gate.
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": "/home/op/.cmctl/.foreman/task-5/.foreman/ledger.db"})
            )
        ),
        Verdict::Deny(_)
    ));
    // The FLEET's own ledger, outside the worktree: denied (gate first).
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": "/home/op/.cmctl/.foreman/ledger.db"})
            )
        ),
        Verdict::Deny(_)
    ));
    // And a sibling task's worktree is outside THIS one: denied.
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": "/home/op/.cmctl/.foreman/task-9/src/lib.rs"})
            )
        ),
        Verdict::Deny(_)
    ));
    // Prefix stripping must be COMPONENT-BOUNDARY aware: "task-5" is a
    // string-prefix of the sibling "task-50", whose .foreman/ protection a
    // blind replace would erase.
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": "sed -i s/x/y/ /home/op/.cmctl/.foreman/task-50/src/lib.rs"})
            )
        ),
        Verdict::Deny(_)
    ));
    // …and must not strip a prefix whose remainder LEXICALLY ESCAPES the
    // worktree: this names the integration clone, which no name fragment
    // protects on its own.
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": "git -C /home/op/.cmctl/.foreman/task-5/../workdir commit -am x"})
            )
        ),
        Verdict::Deny(_)
    ));
    // Escape detection reads the WHOLE path run, not just the first
    // component: these land on the integration clone too.
    for escaping in [
        "git -C /home/op/.cmctl/.foreman/task-5/./../workdir commit -am x",
        "git -C /home/op/.cmctl/.foreman/task-5/src/../../workdir commit -am x",
    ] {
        assert!(
            matches!(
                evaluate(&c, &call("Bash", json!({ "command": escaping }))),
                Verdict::Deny(_)
            ),
            "must not strip a prefix whose path run escapes: {escaping}"
        );
    }
    // The ordinary shell shape — worktree named, then more command — must
    // still pass (a boundary rule that broke this would re-break the fleet).
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": "cd /home/op/.cmctl/.foreman/task-5 && cargo fmt --check"})
            )
        ),
        Verdict::Allow
    );
}

#[test]
fn policy_write_containment() {
    let c = ctx("anthropic", Some("task/7"));
    // Inside the worktree: allowed.
    assert_eq!(
        evaluate(
            &c,
            &call("Write", json!({"file_path": "/work/task7/src/lib.rs"}))
        ),
        Verdict::Allow
    );
    // Relative paths resolve against the worktree.
    assert_eq!(
        evaluate(&c, &call("Edit", json!({"file_path": "src/lib.rs"}))),
        Verdict::Allow
    );
    // Outside: denied.
    assert!(matches!(
        evaluate(&c, &call("Write", json!({"file_path": "/etc/passwd"}))),
        Verdict::Deny(_)
    ));
    // ../ escape from inside: denied.
    assert!(matches!(
        evaluate(
            &c,
            &call("Write", json!({"file_path": "/work/task7/../other/x.rs"}))
        ),
        Verdict::Deny(_)
    ));
    // The agent's own gates: denied even inside a worktree path.
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": "/work/task7/crates/cosmix-foreman/src/policy.rs"})
            )
        ),
        Verdict::Deny(_)
    ));
    // …but ONLY the enforcement surface: the rest of the foreman crate is
    // ordinary work — the fleet's own backlog IS foreman development, and a
    // whole-crate gate made every such task impossible (2026-08-18).
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": "/work/task7/crates/cosmix-foreman/src/driver/claude.rs"})
            )
        ),
        Verdict::Allow
    ));
    // Manifest edits escalate (recorded for the operator).
    assert!(matches!(
        evaluate(
            &c,
            &call("Write", json!({"file_path": "/work/task7/Cargo.toml"}))
        ),
        Verdict::Escalate(_)
    ));
}

#[test]
fn policy_allows_dependency_add_remove_and_repin_in_task_scoped_manifest() {
    let repo = PolicyRepo::new();
    let c = repo.ctx(&["own-crate"]);
    let own = repo.path("src/crates/own-crate/Cargo.toml");

    // Edit and whole-file Write are both judged from the complete resulting
    // bytes, and ordinary dependency changes are open inside existing scope.
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Edit",
                json!({
                    "file_path": &own,
                    "old_string": "[dependencies]\n",
                    "new_string": "[dependencies]\nserde = \"1\"\n"
                })
            )
        ),
        Verdict::Allow
    );
    for proposed in [
        OWN_MANIFEST.replace("anyhow = \"1\"\n", ""),
        OWN_MANIFEST.replace("anyhow = \"1\"", "anyhow = \"2\""),
    ] {
        assert_eq!(
            evaluate(
                &c,
                &call("Write", json!({"file_path": &own, "content": proposed}))
            ),
            Verdict::Allow
        );
    }
}

#[test]
fn policy_refuses_manifest_edit_outside_task_crate_scope() {
    let repo = PolicyRepo::new();
    let c = repo.ctx(&["own-crate"]);
    let own = repo.path("src/crates/own-crate/Cargo.toml");
    let other = repo.path("src/crates/other-crate/Cargo.toml");
    let proposed = OWN_MANIFEST.replace("anyhow = \"1\"", "anyhow = \"2\"");

    // Uncommitted work cannot widen authority between tool calls.
    std::fs::write(
        repo.path("src/crates/own-crate/src/lib.rs"),
        "pub const NAME: &str = \"changed by task\";\n",
    )
    .unwrap();
    let branch_scoped = repo.ctx(&[]);
    let uncommitted = evaluate(
        &branch_scoped,
        &call("Write", json!({"file_path": &own, "content": &proposed})),
    );
    assert!(
        matches!(&uncommitted, Verdict::Escalate(reason) if reason.contains("commit your change")),
        "uncommitted change must not widen crate scope: {uncommitted:?}"
    );

    // Once the non-manifest work is durable in branch history, the task need
    // not repeat the crate name through operator-owned scope.
    run_git(&repo.root, &["add", "src/crates/own-crate/src/lib.rs"]);
    run_git(&repo.root, &["commit", "-m", "change own crate"]);
    assert_eq!(
        evaluate(
            &branch_scoped,
            &call("Write", json!({"file_path": &own, "content": &proposed}))
        ),
        Verdict::Allow
    );

    // The same dependency edit is refused when the task does not own the crate.
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({
                    "file_path": &other,
                    "content": format!("{OTHER_MANIFEST}\n[dependencies]\nserde = \"1\"\n")
                })
            )
        ),
        Verdict::Escalate(_)
    ));

    // Free-form prose has no authority. A task saying "do not modify
    // other-crate" must not authorise other-crate's manifest.
    let prose_only = repo.ctx(&[]);
    assert!(matches!(
        evaluate(
            &prose_only,
            &call(
                "Write",
                json!({
                    "file_path": &other,
                    "content": format!("{OTHER_MANIFEST}\n[dependencies]\nserde = \"1\"\n")
                })
            )
        ),
        Verdict::Escalate(_)
    ));
}

#[test]
fn restrictive_manifest_policy_is_opt_in_and_uses_proposed_content() {
    let repo = PolicyRepo::new();
    let mut c = repo.ctx(&["own-crate"]);
    c.restrict_manifest_edits = true;
    let own = repo.path("src/crates/own-crate/Cargo.toml");
    let bumped = OWN_MANIFEST.replace("version = \"0.2.3\"", "version = \"0.2.4\"");

    assert_eq!(
        evaluate(
            &c,
            &call("Write", json!({"file_path": &own, "content": &bumped}))
        ),
        Verdict::Allow
    );

    let bump_and_dependency = bumped.replace("anyhow = \"1\"", "anyhow = \"2\"");
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": &own, "content": bump_and_dependency})
            )
        ),
        Verdict::Escalate(_)
    ));
    for invalid in [
        OWN_MANIFEST.replace("0.2.3", "0.2.2"),
        OWN_MANIFEST.replace("0.2.3", "1.0.0"),
    ] {
        assert!(matches!(
            evaluate(
                &c,
                &call("Write", json!({"file_path": &own, "content": invalid}))
            ),
            Verdict::Escalate(_)
        ));
    }
}

#[test]
fn policy_refuses_its_gate_file_even_when_foreman_crate_is_task_scoped() {
    let repo = PolicyRepo::new();
    let c = repo.ctx(&["cosmix-foreman"]);
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({
                    "file_path": repo.path("src/crates/cosmix-foreman/src/policy.rs"),
                    "content": "gate replacement"
                })
            )
        ),
        Verdict::Deny(reason) if reason.contains("agents never modify their gates")
    ));
}

#[test]
fn project_policy_uses_manifest_branch_and_package_shapes() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path();
    let manifest = "[package]\nname = \"root-demo\"\nversion = \"0.1.0\"\nedition = \"2024\"\n";
    std::fs::write(root.join("Cargo.toml"), manifest).unwrap();
    std::fs::create_dir(root.join("src")).unwrap();
    std::fs::write(root.join("src/lib.rs"), "pub fn demo() {}\n").unwrap();
    run_git(root, &["init", "-b", "trunk"]);
    run_git(root, &["config", "user.email", "fixture@example.com"]);
    run_git(root, &["config", "user.name", "Policy Fixture"]);
    run_git(root, &["add", "."]);
    run_git(root, &["commit", "-m", "fixture"]);
    run_git(root, &["checkout", "-b", "change/7"]);

    let c = PolicyContext {
        task_id: 7,
        worktree: root.to_path_buf(),
        branch: Some("change/7".into()),
        provider: "anthropic".into(),
        integration_base: git_stdout(root, &["rev-parse", "trunk"]),
        integration_branch: "trunk".into(),
        task_ref_template: "change/{id}".into(),
        package_manifest_template: Some("Cargo.toml".into()),
        restrict_manifest_edits: false,
        task_crates: vec!["root-demo".into()],
    };
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({
                    "file_path": root.join("Cargo.toml"),
                    "content": manifest.replace("0.1.0", "0.1.1")
                })
            )
        ),
        Verdict::Allow
    );
    let mut no_manifest_shape = c.clone();
    no_manifest_shape.package_manifest_template = None;
    assert!(matches!(
        evaluate(
            &no_manifest_shape,
            &call(
                "Write",
                json!({
                    "file_path": root.join("Cargo.toml"),
                    "content": manifest.replace("0.1.0", "0.1.1")
                })
            )
        ),
        Verdict::Escalate(reason) if reason.contains("no package_manifest_template")
    ));
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": "git fetch origin change/18 && git rebase origin/change/18"})
            )
        ),
        Verdict::Deny(reason) if reason.contains("trunk") && reason.contains("change/{id}")
    ));
    assert_eq!(
        evaluate(
            &c,
            &call("Bash", json!({"command": "git fetch origin task/18"}))
        ),
        Verdict::Allow,
        "legacy task/* must not remain a project-mode policy pattern"
    );
}

#[test]
fn legacy_manifest_shape_matches_desktop_crates() {
    let repo = PolicyRepo::new();
    let mut c = repo.ctx(&["own-crate"]);
    c.package_manifest_template =
        Some(cosmix_foreman::policy::LEGACY_PACKAGE_MANIFEST_TEMPLATE.to_string());
    let manifest = repo.path("desktop/crates/own-crate/Cargo.toml");
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({
                    "file_path": manifest,
                    "content": OWN_MANIFEST.replace("0.2.3", "0.2.4")
                })
            )
        ),
        Verdict::Allow
    );
}

#[test]
fn policy_scope_resolves_the_caller_configured_integration_ref() {
    let repo = PolicyRepo::new();
    assert_eq!(
        resolve_integration_base(&repo.root, "integration").unwrap(),
        git_stdout(&repo.root, &["rev-parse", "integration"])
    );
    assert!(resolve_integration_base(&repo.root, "main").is_err());
}

#[test]
fn policy_task_prose_cannot_designate_a_crate() {
    use std::io::Write;

    let repo = PolicyRepo::new();
    let db = repo.root.join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let task = ledger
        .add_task(
            "prose is not authority",
            "Do not modify other-crate, including its manifest",
            "impl",
            "low",
            &[],
            "none",
        )
        .unwrap();
    let payload = call(
        "Write",
        json!({
            "file_path": repo.path("src/crates/other-crate/Cargo.toml"),
            "content": OTHER_MANIFEST.replace("1.4.0", "1.4.1")
        }),
    );
    let mut child = Command::new(env!("CARGO_BIN_EXE_foreman"))
        .args([
            "--db",
            db.to_str().unwrap(),
            "policy-check",
            "--task",
            &task.to_string(),
            "--worktree",
            repo.root.to_str().unwrap(),
            "--provider",
            "anthropic",
            "--branch",
            "task/7",
            "--integration-base",
            &git_stdout(&repo.root, &["rev-parse", "integration"]),
        ])
        .env("FOREMAN_VERIFY_LANE", repo.root.join("verify.lock"))
        .env("FOREMAN_VERIFY_LANE_WAIT_SECS", "30")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child
        .stdin
        .take()
        .unwrap()
        .write_all(payload.to_string().as_bytes())
        .unwrap();
    let output = child.wait_with_output().unwrap();
    assert_eq!(output.status.code(), Some(2));
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("unrelated to this task"),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let findings = ledger.task_findings(task).unwrap();
    assert_eq!(findings.len(), 1, "the handled refusal remains auditable");
    assert_eq!(findings[0].1, "info");
    assert_eq!(findings[0].2, "policy escalation");
}

#[test]
fn policy_allows_exact_quoted_heredoc_and_matching_lock_bump() {
    let repo = PolicyRepo::new();
    let c = repo.ctx(&["own-crate"]);
    let manifest_path = repo.path("src/crates/own-crate/Cargo.toml");
    let bumped = OWN_MANIFEST.replace("0.2.3", "0.2.4");
    let heredoc = format!("cat <<'MANIFEST' > {manifest_path}\n{bumped}MANIFEST\n");
    assert_eq!(
        evaluate(&c, &call("Bash", json!({"command": heredoc}))),
        Verdict::Allow
    );

    // Model the allowed manifest tool having run, then Cargo's corresponding
    // one-line lock rewrite.
    std::fs::write(&manifest_path, &bumped).unwrap();
    let lock_path = repo.path("src/Cargo.lock");
    let bumped_lock = TEST_LOCK.replacen("version = \"0.2.3\"", "version = \"0.2.4\"", 1);
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": &lock_path, "content": &bumped_lock})
            )
        ),
        Verdict::Allow
    );

    // A registry package sharing the workspace crate's name is not the
    // corresponding lock entry and cannot borrow its authority.
    let registry_bump = TEST_LOCK.replace("version = \"7.0.0\"", "version = \"7.0.1\"");
    let verdict = evaluate(
        &c,
        &call(
            "Write",
            json!({"file_path": &lock_path, "content": registry_bump}),
        ),
    );
    assert!(matches!(
        &verdict,
        Verdict::Escalate(reason) if reason.contains("source-less workspace")
    ));

    // The agent may commit the manifest before Cargo updates the lock. The
    // current manifest remains the consistency authority in that ordering.
    run_git(&repo.root, &["add", "src/crates/own-crate/Cargo.toml"]);
    run_git(&repo.root, &["commit", "-m", "bump own-crate"]);
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Write",
                json!({"file_path": &lock_path, "content": &bumped_lock})
            )
        ),
        Verdict::Allow
    );

    let opaque = format!("sed -i s/0.2.3/0.2.4/ {manifest_path}");
    let verdict = evaluate(&c, &call("Bash", json!({"command": opaque})));
    assert!(matches!(&verdict, Verdict::Escalate(reason) if reason.contains("cannot determine")));

    let inexact = format!("cat extra-input <<'MANIFEST' > {manifest_path}\n{bumped}MANIFEST\n");
    let verdict = evaluate(&c, &call("Bash", json!({"command": inexact})));
    assert!(matches!(&verdict, Verdict::Escalate(reason) if reason.contains("exact whole-file")));

    let fake_cat = format!("/tmp/evil/cat <<'MANIFEST' > {manifest_path}\n{bumped}MANIFEST\n");
    let verdict = evaluate(&c, &call("Bash", json!({"command": fake_cat})));
    assert!(matches!(&verdict, Verdict::Escalate(reason) if reason.contains("literal `cat`")));
}

#[test]
fn policy_shell_manifest_writes_fail_closed_without_proposed_content() {
    let repo = PolicyRepo::new();
    let c = repo.ctx(&["own-crate"]);
    let manifest = repo.path("src/crates/own-crate/Cargo.toml");
    let lock = repo.path("src/Cargo.lock");

    let writes = [
        format!("printf x > {manifest}"),
        format!("printf x >> {manifest}"),
        format!("printf x >| {manifest}"),
        format!("printf x &> {manifest}"),
        format!("printf x &>> {manifest}"),
        format!("cp /tmp/replacement {manifest}"),
        format!("mv /tmp/replacement {manifest}"),
        format!("install -m 0644 /tmp/replacement {manifest}"),
        format!("ln -sf /tmp/replacement {manifest}"),
        format!("rsync -a /tmp/replacement {manifest}"),
        format!("dd if=/tmp/replacement of={manifest}"),
        format!("printf x | tee {manifest}"),
        format!("printf x | tee -a {manifest}"),
        format!("sed -E -i s/0.2.3/0.2.4/ {manifest}"),
        format!("perl -pi -e s/0.2.3/0.2.4/ {manifest}"),
        format!("awk '{{ print }}' {manifest} > /tmp/Cargo.next && mv /tmp/Cargo.next {manifest}"),
        format!("python -m tomlkit {manifest}"),
        format!("ruby /tmp/rewrite.rb {manifest}"),
        format!("git restore -- {manifest}"),
        format!("git checkout -- {manifest}"),
    ];
    for command in writes {
        let verdict = evaluate(&c, &call("Bash", json!({"command": &command})));
        assert!(
            matches!(&verdict, Verdict::Escalate(reason) if reason.contains("cannot determine")),
            "manifest write must fail closed for {command:?}, got {verdict:?}"
        );
    }

    for command in [
        "cargo add serde".to_string(),
        "cargo remove serde".to_string(),
        "cargo set-version 0.2.4".to_string(),
        "cargo update".to_string(),
        "cargo generate-lockfile".to_string(),
        "cargo upgrade".to_string(),
        "CARGO_NET_OFFLINE=true cargo --color always update".to_string(),
    ] {
        let verdict = evaluate(&c, &call("Bash", json!({"command": &command})));
        assert!(
            matches!(&verdict, Verdict::Escalate(reason) if reason.contains("cannot determine")),
            "Cargo manifest writer must fail closed for {command:?}, got {verdict:?}"
        );
    }

    let read_only = [
        format!("cat {manifest}"),
        format!("ls -l {manifest} 2>&1"),
        format!("head -n 2 {manifest}"),
        format!("tail -n 2 {manifest}"),
        format!("wc -l {manifest}"),
        format!("grep version {manifest}"),
        format!("rg version {manifest}"),
        format!("diff {manifest} {manifest}"),
        format!("stat {manifest}"),
        format!("git diff -- {manifest}"),
        format!("git show HEAD:{manifest}"),
        format!("git log -- {manifest}"),
        format!("git blame {manifest}"),
        format!("cargo build --manifest-path {manifest}"),
        format!("cargo check --manifest-path {manifest}"),
        format!("cargo test --manifest-path {manifest} > /tmp/test.log"),
        format!("cargo clippy --manifest-path {manifest}"),
        format!("cargo fmt --manifest-path {manifest}"),
        format!("cargo metadata --manifest-path={manifest}"),
        format!("cargo tree --manifest-path {manifest}"),
        format!("cargo doc --manifest-path {manifest}"),
    ];
    for command in read_only {
        assert_eq!(
            evaluate(&c, &call("Bash", json!({"command": &command}))),
            Verdict::Allow,
            "read-only manifest command must remain allowed: {command:?}"
        );
    }

    // Cargo.lock is controlled too; read-only utilities may inspect it but
    // an unrecognised command cannot act on it.
    assert_eq!(
        evaluate(
            &c,
            &call("Bash", json!({"command": format!("rg version {lock}")}))
        ),
        Verdict::Allow
    );
    assert!(matches!(
        evaluate(
            &c,
            &call("Bash", json!({"command": format!("touch {lock}")}))
        ),
        Verdict::Escalate(_)
    ));
    assert!(matches!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": format!("git diff --output={manifest}")})
            )
        ),
        Verdict::Escalate(_)
    ));
}

#[test]
fn policy_shell_write_targets_with_expansion_fail_closed() {
    let repo = PolicyRepo::new();
    let c = repo.ctx(&["own-crate"]);

    for command in [
        "printf x > src/crates/own-crate/Cargo.tom?",
        "cp /tmp/replacement src/crates/own-crate/Cargo.tom[l]",
        "tee src/crates/own-crate/Cargo.{toml,lock}",
        "cat <<'EOF' > src/crates/own-crate/$NAME\nx\nEOF\n",
    ] {
        let verdict = evaluate(&c, &call("Bash", json!({"command": command})));
        assert!(
            matches!(&verdict, Verdict::Escalate(reason) if reason.contains("glob/expansion")),
            "expanded write target must fail closed for {command:?}, got {verdict:?}"
        );
    }

    for command in [
        "ls src/crates/*/Cargo.toml",
        "grep -r version src/crates/*/Cargo.toml",
    ] {
        assert_eq!(
            evaluate(&c, &call("Bash", json!({"command": command}))),
            Verdict::Allow,
            "read-only glob must remain allowed: {command:?}"
        );
    }
}

#[test]
fn policy_bash_rules() {
    let c = ctx("anthropic", Some("task/7"));
    assert_eq!(
        evaluate(&c, &call("Bash", json!({"command": "cargo test"}))),
        Verdict::Allow
    );
    assert_eq!(
        evaluate(
            &c,
            &call(
                "Bash",
                json!({"command": "cargo test --manifest-path crates/x/Cargo.toml > /tmp/test.log"})
            )
        ),
        Verdict::Allow
    );
    // Only the shared fleet repo and this task's branch are a valid push
    // destination. `origin` remains denied even when the refspec is right.
    let push_repo = PushPolicyRepo::new();
    let push_ctx = push_repo.ctx();
    assert_eq!(
        evaluate(
            &push_ctx,
            &call(
                "Bash",
                json!({"command": format!("git push {} task/7", push_repo.shared.display())})
            )
        ),
        Verdict::Allow
    );
    assert!(matches!(
        evaluate(
            &push_ctx,
            &call("Bash", json!({"command": "git push origin task/7"}))
        ),
        Verdict::Deny(reason) if reason.contains("canonical/public")
    ));
    assert!(matches!(
        evaluate(
            &push_ctx,
            &call("Bash", json!({"command": "git push origin main"}))
        ),
        Verdict::Deny(_)
    ));
    assert!(matches!(
        evaluate(
            &push_ctx,
            &call("Bash", json!({"command": "git push --force origin task/7"}))
        ),
        Verdict::Deny(_)
    ));
    assert!(matches!(
        evaluate(
            &push_ctx,
            &call("Bash", json!({"command": "git push -f origin task/7"}))
        ),
        Verdict::Deny(_)
    ));
    for command in [
        "git pull --rebase origin task/18",
        "git fetch origin task/18 && git reset --hard origin/task/18",
        "git fetch origin main && git rebase origin/task/18",
        "git fetch origin main && git rebase origin/task/foo/bar",
    ] {
        assert!(matches!(
            evaluate(&c, &call("Bash", json!({"command": command}))),
            Verdict::Deny(reason) if reason.contains("shared fleet repo")
        ));
    }
    assert_eq!(
        evaluate(
            &c,
            &call("Bash", json!({"command": "git fetch origin main"}))
        ),
        Verdict::Allow
    );
    // No branch on the task → no pushes at all.
    let nb = ctx("anthropic", None);
    assert!(matches!(
        evaluate(
            &nb,
            &call("Bash", json!({"command": "git push origin whatever"}))
        ),
        Verdict::Deny(_)
    ));
    // Recursive delete escalates.
    assert!(matches!(
        evaluate(&c, &call("Bash", json!({"command": "rm -rf target"}))),
        Verdict::Escalate(_)
    ));
    // Shelling into the gates is denied.
    assert!(matches!(
        evaluate(
            &c,
            &call("Bash", json!({"command": "echo x >> .foreman/ledger.db"}))
        ),
        Verdict::Deny(_)
    ));
}

#[test]
fn policy_push_denial_files_reasoned_finding() {
    use std::io::Write;

    let repo = PushPolicyRepo::new();
    let db = repo.shared.parent().unwrap().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let task = ledger
        .add_task("push guard", "spec", "impl", "low", &[], "none")
        .unwrap();
    let payload = call(
        "Bash",
        json!({"command": format!("git push origin task/{task}")}),
    );
    let mut child = Command::new(env!("CARGO_BIN_EXE_foreman"))
        .args([
            "--db",
            db.to_str().unwrap(),
            "policy-check",
            "--task",
            &task.to_string(),
            "--worktree",
            repo.worktree.to_str().unwrap(),
            "--provider",
            "anthropic",
            "--branch",
            &format!("task/{task}"),
            "--integration-base",
            "HEAD",
        ])
        .env(
            "FOREMAN_VERIFY_LANE",
            repo.shared.parent().unwrap().join("verify.lock"),
        )
        .env("FOREMAN_VERIFY_LANE_WAIT_SECS", "30")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child
        .stdin
        .take()
        .unwrap()
        .write_all(payload.to_string().as_bytes())
        .unwrap();
    let output = child.wait_with_output().unwrap();
    assert_eq!(output.status.code(), Some(2));
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("canonical/public remote"), "{stderr}");
    let findings = ledger.open_findings(10).unwrap();
    assert!(findings.iter().any(|(_, found_task, _, title, body)| {
        *found_task == Some(task)
            && title == "policy deny"
            && body.contains("canonical/public remote")
    }));
}

#[test]
fn policy_zai_secret_reads() {
    let z = ctx("zai", Some("task/7"));
    assert!(matches!(
        evaluate(&z, &call("Read", json!({"file_path": "/work/task7/.env"}))),
        Verdict::Deny(_)
    ));
    assert!(matches!(
        evaluate(&z, &call("Bash", json!({"command": "cat ~/.ssh/id_rsa"}))),
        Verdict::Deny(_)
    ));
    assert_eq!(
        evaluate(
            &z,
            &call("Read", json!({"file_path": "/work/task7/src/lib.rs"}))
        ),
        Verdict::Allow
    );
    // The same reads are fine for the default provider.
    let a = ctx("anthropic", Some("task/7"));
    assert_eq!(
        evaluate(&a, &call("Read", json!({"file_path": "/work/task7/.env"}))),
        Verdict::Allow
    );
}

#[test]
fn policy_unknown_tools_pass() {
    let c = ctx("anthropic", None);
    assert_eq!(
        evaluate(&c, &call("mcp__foreman__task_next", json!({}))),
        Verdict::Allow
    );
}

// ---- reservation ----

/// The free lane must not be gated by the metered lane's ceiling.
///
/// The runner discards `cost_usd` for GLM (the claude CLI prices remapped
/// Z.ai traffic at Anthropic rates, which is fiction), so a GLM run can
/// never spend a cent against the dollar ceiling. Reserving dollars for it
/// anyway means that once the claude lane fills the ceiling, the free lane
/// is refused too and the fleet stops completely.
///
/// Observed live 2026-08-19: at $96.43 of a $100 ceiling, dispatch routed
/// tasks 9 and 10 to glm and both were refused with "$96.43 spent + $5.00
/// requested exceeds the $100.00 daily ceiling". Nothing ran for the rest
/// of the UTC day.
#[test]
fn free_lane_is_not_gated_by_the_dollar_ceiling() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let governor = Governor::with_limits(&db, 10.0, 1_000_000);

    // Fill the dollar ceiling with a metered hold.
    let full = Budget {
        max_budget_usd: Some(10.0),
        max_output_tokens: Some(1_000),
        ..Default::default()
    };
    governor
        .reserve(&ledger, "claude@1", Some(1), &full, AgentKind::Claude)
        .expect("the metered hold itself fits");

    // A metered run now has no room — the ceiling is doing its job.
    let err = governor
        .reserve(&ledger, "claude@2", Some(2), &full, AgentKind::Claude)
        .unwrap_err();
    assert!(
        format!("{err:#}").contains("reservation refused"),
        "the dollar ceiling must still bind the metered lane: {err:#}"
    );

    // The unmetered lanes must still be admitted at the same instant.
    //
    // An EXPLICIT non-zero cap is used deliberately rather than
    // `Budget::default()`: the default reserve is configurable through the
    // governor's policy snapshot, so pinning $6 keeps this test independent
    // of that separate mechanism.
    // Token holds are pinned small and explicit so this test can only ever
    // fail on the DOLLAR dimension; left at the env default, three holds
    // collide with the token ceiling and the refusal has nothing to do with
    // what is under test.
    let asks_six = Budget {
        max_budget_usd: Some(6.0),
        max_output_tokens: Some(1_000),
        ..Default::default()
    };
    for (who, kind) in [("glm@3", AgentKind::Glm), ("codex@4", AgentKind::Codex)] {
        governor
            .reserve(&ledger, who, Some(3), &asks_six, kind)
            .unwrap_or_else(|e| panic!("{who} must run while the metered ceiling is full: {e:#}"));
    }

    // And they must hold no dollars, or a queue of them would gate each
    // other. Exactly $10 also refutes "reserve $0 for everyone": under that
    // implementation the claude@2 refusal above would not have happened.
    let s = governor.status(&ledger).unwrap();
    assert!(
        (s.reserved_usd - 10.0).abs() < 1e-9,
        "the free lanes must reserve $0, got total {:?}",
        s.reserved_usd
    );
}

/// Requesting $0 is not enough — the dollar dimension must be OFF.
///
/// The ledger's test is `spent + held + requested > ceiling`, so once spend
/// sits ABOVE the ceiling even a $0 request is refused and the free lane
/// halts again. Spend gets there routinely: a lowered ceiling, a
/// `--no-governor` run, or actuals overshooting their hold (live run 81 cost
/// $5.09 against a $5 hold). Found by the codex review arm 2026-08-19 as the
/// residual left by the first cut of the fix.
#[test]
fn free_lane_runs_even_when_spend_is_over_the_ceiling() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();

    // Bank real spend ABOVE the ceiling, the way an overshooting run does.
    let task = ledger
        .add_task("t", "spec", "impl", "low", &[], "none")
        .unwrap();
    let run = ledger
        .start_run(task, AgentKind::Claude, None, None)
        .unwrap();
    ledger
        .finish_run(
            run,
            &RunOutcome {
                stop: StopReason::Done,
                result: None,
                error: None,
                usage: Usage {
                    input_tokens: 0,
                    fresh_input_tokens: None,
                    output_tokens: 10,
                    cost_usd: Some(12.0),
                    cache_read_input_tokens: None,
                    cache_creation_input_tokens: None,
                },
                session_ref: None,
                terminal_session_ref: None,
                usage_observed: true,
                output_observed: true,
                resume_failure: None,
            },
            1,
        )
        .unwrap();

    let governor = Governor::with_limits(&db, 10.0, 1_000_000);
    // Metered lane: correctly refused, $12 spent against a $10 ceiling.
    let err = governor
        .reserve(
            &ledger,
            "claude@1",
            Some(task),
            &Budget::default(),
            AgentKind::Claude,
        )
        .unwrap_err();
    assert!(
        format!("{err:#}").contains("daily ceiling"),
        "over-ceiling spend must still bind the metered lane: {err:#}"
    );

    // Unmetered lane: admitted anyway. It cannot have contributed to the
    // $12 and cannot add to it.
    governor
        .reserve(
            &ledger,
            "glm@2",
            Some(task),
            &Budget::default(),
            AgentKind::Glm,
        )
        .expect("the free lane must run even with spend over the ceiling");
}

/// A codex run in a git WORKTREE must be granted the main checkout's .git,
/// or it cannot commit and the branch contract bounces every task.
///
/// Live on the first real codex run (task 13, 2026-08-19): the agent did the
/// work correctly — fmt, clippy and 87 tests green — then reported "a sandbox
/// permission mismatch has blocked the required commit", because a worktree's
/// `.git` is a FILE pointing at `<main>/.git/worktrees/<name>`, which sits
/// outside the workspace that `--sandbox workspace-write` makes writable.
#[test]
fn codex_worktree_gets_the_real_git_dir() {
    let tmp = tempfile::tempdir().unwrap();
    let main = tmp.path().join("main");
    std::fs::create_dir(&main).unwrap();
    let git = |args: &[&str], cwd: &std::path::Path| {
        let out = std::process::Command::new("git")
            .args(args)
            .current_dir(cwd)
            .output()
            .unwrap();
        assert!(out.status.success(), "git {args:?}: {out:?}");
    };
    git(&["init", "-q", "-b", "main"], &main);
    git(&["config", "user.email", "t@example.com"], &main);
    git(&["config", "user.name", "t"], &main);
    std::fs::write(main.join("f"), "x").unwrap();
    git(&["add", "f"], &main);
    git(&["commit", "-qm", "c"], &main);

    // The worktree is a SIBLING of the repo, as the refinery builds them.
    let wt = tmp.path().join("task-1");
    git(
        &[
            "worktree",
            "add",
            "-q",
            wt.to_str().unwrap(),
            "-b",
            "task/1",
        ],
        &main,
    );

    // A worktree's own `.git` is a file, not a directory — the whole reason
    // the sandbox blocks the commit.
    assert!(
        wt.join(".git").is_file(),
        "precondition: a worktree's .git must be a file pointer"
    );

    let resolved = cosmix_foreman::driver::codex::git_common_dir(&wt)
        .expect("git must resolve a common dir inside a worktree");
    let resolved = std::path::Path::new(&resolved).canonicalize().unwrap();
    assert_eq!(
        resolved,
        main.join(".git").canonicalize().unwrap(),
        "must resolve to the MAIN checkout's .git, where objects and refs live"
    );
    // …and it must NOT be inside the worktree, or granting it would be a
    // no-op and the commit would still fail.
    assert!(
        !resolved.starts_with(wt.canonicalize().unwrap()),
        "the granted dir must be outside the worktree: {resolved:?}"
    );

    // A plain checkout resolves to its own .git; a non-repo yields None, so
    // the sandbox is never widened without cause.
    assert!(cosmix_foreman::driver::codex::git_common_dir(&main).is_some());
    let bare = tmp.path().join("not-a-repo");
    std::fs::create_dir(&bare).unwrap();
    assert!(cosmix_foreman::driver::codex::git_common_dir(&bare).is_none());

    // THE LOAD-BEARING PART: the grant must reach the actual command line.
    // Checking git_common_dir alone would stay green with the grant deleted
    // from the argv entirely — which is the bug, not the helper.
    let argv = CodexDriver::new().args_for("p", &Budget::default(), &wt);
    let at = argv
        .iter()
        .position(|a| a == "--add-dir")
        .expect("codex argv must carry the sandbox grant in a worktree");
    assert_eq!(
        argv[0], "exec",
        "--add-dir is an exec-level flag; it must follow the subcommand"
    );
    assert_eq!(at, 1, "grant must sit immediately after `exec`: {argv:?}");
    assert_eq!(
        std::path::Path::new(&argv[2]).canonicalize().unwrap(),
        main.join(".git").canonicalize().unwrap()
    );
    // Still sandboxed: the grant widens the sandbox, it must not replace it.
    assert!(
        argv.windows(2)
            .any(|w| w[0] == "--sandbox" && w[1] == "workspace-write"),
        "the grant must not have displaced the sandbox mode: {argv:?}"
    );
    let read_only =
        CodexDriver::new()
            .with_sandbox("read-only")
            .args_for("review", &Budget::default(), &wt);
    assert!(
        !read_only.iter().any(|a| a == "--add-dir"),
        "a read-only reviewer must not receive a writable external git-dir grant: {read_only:?}"
    );
    // Outside a repo there is no git grant. Build-cache grants may still be
    // present when the dispatch environment sets CARGO_TARGET_DIR.
    let argv = CodexDriver::new().args_for("p", &Budget::default(), &bare);
    assert!(
        !argv
            .windows(2)
            .any(|w| w[0] == "--add-dir" && std::path::Path::new(&w[1]) == main.join(".git")),
        "must not add a git grant outside a repo: {argv:?}"
    );
}

/// Every lane must have a containment mechanism under `--policy`.
///
/// `--policy` is passed unconditionally by the dispatch unit, and it used to
/// REFUSE codex outright ("--policy is hook-based and needs a claude/glm
/// session"). That refusal had no test, and its effect was that a codex rung
/// on the ladder could never start — which is why codex sat off the ladder.
/// A lane is now either hook-gated or sandbox-contained; there is no third
/// answer, and a new lane must pick one rather than silently falling through
/// to "refused" or, worse, to "uncontained".
#[test]
fn every_lane_has_a_policy_mechanism() {
    use cosmix_foreman::policy::{PolicyMechanism, policy_mechanism};

    // The claude CLI drives both of these, so both get per-call verdicts.
    assert_eq!(
        policy_mechanism(AgentKind::Claude),
        PolicyMechanism::HookGate
    );
    assert_eq!(policy_mechanism(AgentKind::Glm), PolicyMechanism::HookGate);

    // Codex has no hook surface; it is contained by its driver's
    // `--sandbox workspace-write`, verified by effect to override the user
    // config's danger-full-access.
    assert_eq!(
        policy_mechanism(AgentKind::Codex),
        PolicyMechanism::OwnSandbox
    );

    // And the driver must actually still ASK for that sandbox — the whole
    // containment claim for this lane rests on the flag being present.
    let args = CodexDriver::new().build_args("prompt", &Budget::default());
    let sandbox = args
        .iter()
        .position(|a| a == "--sandbox")
        .map(|i| args[i + 1].clone());
    assert_eq!(
        sandbox.as_deref(),
        Some("workspace-write"),
        "codex containment depends on this flag; argv was {args:?}"
    );
}

#[test]
fn resumable_cli_drivers_pass_the_recorded_session() {
    let claude =
        ClaudeDriver::new().build_resume_args("claude-session", "prompt", &Budget::default());
    assert!(
        claude
            .windows(2)
            .any(|pair| pair == ["--resume", "claude-session"]),
        "Claude resume argv missing: {claude:?}"
    );

    let codex = CodexDriver::new().build_resume_args("codex-session", "prompt", &Budget::default());
    assert!(
        codex
            .windows(2)
            .any(|pair| pair == ["resume", "codex-session"]),
        "Codex resume argv missing: {codex:?}"
    );
}

/// The resume argv shapes handed to the REAL vendor CLIs must parse.
///
/// A shape assertion cannot see a clap rejection: the first cut of task 70's
/// codex resume put `--sandbox`/`--add-dir` after the `exec resume`
/// subcommand, which reads perfectly as a string vector and is refused
/// outright by codex-cli ("error: unexpected argument '--sandbox' found").
/// So this drives the installed binary and asserts only that argv PARSING
/// succeeded — the run is deliberately made to die immediately afterwards on
/// codex's own trusted-directory check by giving it a non-repo cwd, so the
/// test costs no tokens and touches no network.
///
/// Skipped when the binary is absent (developer machines, CI images without
/// the vendor CLI), and when the child does not exit promptly — an
/// environment quirk must not turn into a red test.
#[test]
fn codex_resume_argv_is_accepted_by_the_installed_cli() {
    let Some(codex_bin) = which("codex") else {
        eprintln!("codex not installed; skipping the real-parser gate");
        return;
    };
    let tmp = tempfile::tempdir().unwrap();
    // Grants are computed against a real repo; the CWD deliberately is not
    // one, so codex refuses on the trusted-directory check AFTER parsing.
    let repo = tmp.path().join("repo");
    std::fs::create_dir(&repo).unwrap();
    std::process::Command::new("git")
        .args(["init", "-q"])
        .current_dir(&repo)
        .status()
        .unwrap();
    let not_a_repo = tmp.path().join("elsewhere");
    std::fs::create_dir(&not_a_repo).unwrap();

    let args = CodexDriver::new()
        .with_model(Some("gpt-5.6-sol".into()))
        .resume_args_for(
            "00000000-0000-0000-0000-000000000000",
            "re-judge your findings",
            &Budget::default(),
            &repo,
        );
    let mut child = std::process::Command::new(&codex_bin)
        .args(&args)
        .current_dir(&not_a_repo)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .unwrap();
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(30);
    loop {
        match child.try_wait().unwrap() {
            Some(_) => break,
            None if std::time::Instant::now() >= deadline => {
                let _ = child.kill();
                let _ = child.wait();
                eprintln!("codex did not exit promptly; skipping the real-parser gate");
                return;
            }
            None => std::thread::sleep(std::time::Duration::from_millis(50)),
        }
    }
    let out = child.wait_with_output().unwrap();
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        !text.contains("unexpected argument") && !text.contains("Usage: codex exec"),
        "codex refused the resume argv at parse time.\nargv: {args:?}\noutput: {text}"
    );
}

fn which(program: &str) -> Option<std::path::PathBuf> {
    std::env::var_os("PATH").and_then(|path| {
        std::env::split_paths(&path)
            .map(|dir| dir.join(program))
            .find(|candidate| candidate.is_file())
    })
}

/// `meters_dollars()` must agree with each lane's driver, which is the
/// ground truth for "does a real dollar figure exist here".
///
/// The first cut of this predicate was derived from the GLM incident rather
/// than from the drivers, and shipped green with `Codex => true` — a phantom
/// $5 hold on a lane that reports no cost at all. Both review arms caught it
/// independently; this test is what stops the next lane repeating it.
#[test]
fn lane_metering_matches_drivers() {
    // Built directly rather than through `driver::build`, which resolves a
    // real Z.ai token for the GLM lane; the capability answer does not
    // depend on the credential.
    let drivers: Vec<(AgentKind, Box<dyn Executor>)> = vec![
        (AgentKind::Claude, Box::new(ClaudeDriver::new())),
        (AgentKind::Glm, Box::new(ClaudeDriver::glm("test-token"))),
        (AgentKind::Codex, Box::new(CodexDriver::new())),
    ];
    for (kind, driver) in drivers {
        assert_eq!(
            kind,
            driver.kind(),
            "test wired the wrong driver for {}",
            kind.as_str()
        );
        assert_eq!(
            kind.meters_dollars(),
            driver.capabilities().enforces_cost_cap,
            "{}: meters_dollars() disagrees with its driver's \
             enforces_cost_cap — one of them is lying about whether this \
             lane can produce a dollar figure",
            kind.as_str()
        );
    }
}

/// Token holds are real for every lane — the fix above must not have
/// exempted the free lane from the token ceiling as a side effect.
#[test]
fn free_lane_still_holds_tokens() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let governor = Governor::with_limits(&db, 10.0, 600_000);

    // EXPLICIT token caps, not `Budget::default()`: the default reserve is
    // configurable through the governor's policy snapshot. 400k x 2 > 600k
    // regardless of that separate mechanism.
    let asks_400k = Budget {
        max_output_tokens: Some(400_000),
        ..Default::default()
    };

    governor
        .reserve(&ledger, "glm@1", Some(1), &asks_400k, AgentKind::Glm)
        .expect("first free-lane hold fits");
    let s = governor.status(&ledger).unwrap();
    assert_eq!(
        s.reserved_tokens, 400_000,
        "the free lane must still hold output tokens: {s:?}"
    );

    // The second hold crosses the 600k ceiling → refused on TOKENS, proving
    // the free lane is still governed. Asserting the DISTINGUISHING text,
    // not just "reservation refused": the dollar dimension is off for this
    // lane, so a refusal naming dollars would mean the fix leaked.
    let err = governor
        .reserve(&ledger, "glm@2", Some(2), &asks_400k, AgentKind::Glm)
        .unwrap_err();
    let err = format!("{err:#}");
    assert!(
        err.contains("output tokens"),
        "the token ceiling must still bind the free lane: {err}"
    );
}

#[test]
fn reservation_holds_headroom_atomically() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let governor = Governor::with_limits(&db, 10.0, 1_000_000);

    // First run reserves its explicit cap.
    let budget_a = Budget {
        max_budget_usd: Some(6.0),
        ..Default::default()
    };
    let a = governor
        .reserve(&ledger, "w1", Some(1), &budget_a, AgentKind::Claude)
        .unwrap();

    // A second identical hold would exceed the $10 ceiling → refused, even
    // though nothing has been SPENT yet.
    let err = governor
        .reserve(&ledger, "w2", Some(2), &budget_a, AgentKind::Claude)
        .unwrap_err();
    assert!(
        format!("{err:#}").contains("reservation refused"),
        "{err:#}"
    );

    // A smaller hold still fits.
    let budget_b = Budget {
        max_budget_usd: Some(3.0),
        ..Default::default()
    };
    let b = governor
        .reserve(&ledger, "w2", Some(2), &budget_b, AgentKind::Claude)
        .unwrap();

    // Status shows both holds; admit (the MCP gate) sees them too.
    let s = governor.status(&ledger).unwrap();
    assert!((s.reserved_usd - 9.0).abs() < 1e-9, "{s:?}");
    let err = format!("{:#}", governor.admit(&ledger).unwrap_err());
    assert!(err.contains("reserved"), "{err}");

    // Releases free the headroom.
    governor.release(&ledger, a).unwrap();
    governor.release(&ledger, b).unwrap();
    governor.admit(&ledger).unwrap();
    governor.release(&ledger, a).expect("release is idempotent");
}

fn insert_reservation(
    db: &std::path::Path,
    claimant: &str,
    usd: f64,
    tokens: i64,
    pid: Option<i64>,
    pid_start: Option<i64>,
    created_at: &str,
) {
    let conn = rusqlite::Connection::open(db).unwrap();
    conn.execute(
        "INSERT INTO reservations
             (claimant, task_id, usd, tokens, pid, pid_start, created_at)
         VALUES (?1, NULL, ?2, ?3, ?4, ?5, ?6)",
        rusqlite::params![claimant, usd, tokens, pid, pid_start, created_at],
    )
    .unwrap();
}

#[test]
fn governor_status_and_reserve_sweep_young_dead_pid_reservations() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let governor = Governor::with_limits(&db, 10.0, 1_000_000);
    let now = chrono::Utc::now().to_rfc3339();

    // Deliberately younger than the four-hour fallback. The impossible pid
    // makes the owner absence deterministic without depending on pid reuse.
    insert_reservation(
        &db,
        "dead-before-status",
        9.0,
        900_000,
        Some(999_999_999),
        None,
        &now,
    );
    let status = governor.status(&ledger).unwrap();
    assert_eq!(
        status.reserved_usd, 0.0,
        "status must sweep a young dead hold"
    );
    assert_eq!(status.reserved_tokens, 0);

    // Plant another young dead hold after status, so reserve's independent
    // call site must widen its sweep too. Without that sweep, 9 + 9 exceeds
    // the $10 ceiling and this request is refused.
    insert_reservation(
        &db,
        "dead-before-reserve",
        9.0,
        900_000,
        Some(999_999_999),
        None,
        &chrono::Utc::now().to_rfc3339(),
    );
    let id = governor
        .reserve(
            &ledger,
            "live",
            None,
            &Budget {
                max_budget_usd: Some(9.0),
                max_output_tokens: Some(900_000),
                ..Default::default()
            },
            AgentKind::Claude,
        )
        .expect("reserve must clear a young dead hold before checking headroom");
    governor.release(&ledger, id).unwrap();
}

#[test]
fn reservation_sweep_keeps_a_long_running_owner_and_fences_pid_reuse() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let governor = Governor::with_limits(&db, 10.0, 1_000_000);
    let pid = std::process::id() as i64;
    let pid_start = cosmix_foreman::procutil::starttime(pid).expect("test pid has /proc stat");
    let old = (chrono::Utc::now() - chrono::Duration::hours(5)).to_rfc3339();

    // Old enough for the TTL arm, but held by this still-running process.
    insert_reservation(
        &db,
        "live-long-run",
        4.0,
        400_000,
        Some(pid),
        Some(pid_start),
        &old,
    );
    // Same numeric pid, different process generation: this represents the
    // stale hold left before a pid was recycled. pid_start, not pid alone,
    // must stop that dead generation pinning headroom.
    insert_reservation(
        &db,
        "reused-pid-generation",
        3.0,
        300_000,
        Some(pid),
        Some(pid_start + 1),
        &chrono::Utc::now().to_rfc3339(),
    );

    let status = governor.status(&ledger).unwrap();
    assert_eq!(status.reserved_usd, 4.0);
    assert_eq!(status.reserved_tokens, 400_000);
    let conn = rusqlite::Connection::open(&db).unwrap();
    let remaining: Vec<String> = conn
        .prepare("SELECT claimant FROM reservations ORDER BY claimant")
        .unwrap()
        .query_map([], |row| row.get(0))
        .unwrap()
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(remaining, vec!["live-long-run"]);
}

#[test]
fn terminal_unpriced_orphan_spend_uses_its_recorded_dollar_reservation() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let task = ledger
        .add_task("unpriced orphan", "spec", "impl", "low", &[], "none")
        .unwrap();
    let run = ledger
        .start_run(task, AgentKind::Claude, None, None)
        .unwrap();
    let conn = rusqlite::Connection::open(&db).unwrap();
    conn.execute("UPDATE runs SET reserved_usd = 4.25 WHERE id = ?1", [run])
        .unwrap();
    ledger
        .update_run_usage(
            run,
            &Usage {
                input_tokens: 1200,
                output_tokens: 300,
                cost_usd: None,
                ..Usage::default()
            },
        )
        .unwrap();

    let since = "2000-01-01T00:00:00+00:00";
    assert_eq!(
        conn.query_row("SELECT cost_usd FROM runs WHERE id = ?1", [run], |row| {
            row.get::<_, Option<f64>>(0)
        },)
            .unwrap(),
        None,
        "the regression fixture must genuinely leave cost_usd NULL",
    );
    assert_eq!(
        ledger.usage_since(since).unwrap(),
        (0.0, 300),
        "an open production run is still covered by its live reservation"
    );

    // The orphan reaper terminalises this shape without inventing a price.
    // Preserve that exact NULL while marking the run terminal.
    conn.execute(
        "UPDATE runs SET verdict = 'error', delivery = 'harness_error',
                         error = 'claim owner died'
         WHERE id = ?1",
        [run],
    )
    .unwrap();
    assert_eq!(
        conn.query_row("SELECT cost_usd FROM runs WHERE id = ?1", [run], |row| {
            row.get::<_, Option<f64>>(0)
        },)
            .unwrap(),
        None,
        "terminalisation must not turn an unknown price into zero or a fixture cost",
    );

    let governor = Governor::with_limits(&db, 5.0, 1_000_000);
    let status = governor.status(&ledger).unwrap();
    assert_eq!(status.spend_today_usd, 4.25);
    assert_eq!(status.output_tokens_today, 300);
    let error = governor
        .reserve(
            &ledger,
            "next-run",
            Some(task),
            &Budget {
                max_budget_usd: Some(1.0),
                max_output_tokens: Some(1),
                ..Default::default()
            },
            AgentKind::Claude,
        )
        .unwrap_err();
    assert!(
        format!("{error:#}").contains("$4.25 spent"),
        "the atomic reserve check must use the same orphan charge as status: {error:#}"
    );
}

#[test]
fn reservation_rejects_invalid_explicit_caps() {
    let tmp = tempfile::tempdir().unwrap();
    let db = tmp.path().join("ledger.db");
    let ledger = Ledger::open(&db).unwrap();
    let since = "2000-01-01T00:00:00+00:00";

    // Bad explicit caps are refused at the ledger boundary.
    assert!(
        ledger
            .reserve("evil", None, -100.0, 0, 10.0, 0, since)
            .is_err()
    );
    assert!(
        ledger
            .reserve("evil", None, f64::NAN, 0, 10.0, 0, since)
            .is_err()
    );
}
